---------------------------------------이관관련 쿼리-------------------------------------------

CHECKHINT 값 0으로 변경

------------------------ASYSCONTENTELEMENT-----------------------------
-- ASIS
SELECT CONTENTCLASSID , count(*) AS 갯수 FROM XTORM.ASYSCONTENTELEMENT a GROUP BY CONTENTCLASSID ;

SELECT * FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='LN_CC';
SELECT COUNT(*) FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='LN_CC';
SELECT * FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='DP_CC';
SELECT COUNT(*) FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='DP_CC';
SELECT * FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='CO_CC';
SELECT COUNT(*) FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='CO_CC';
SELECT * FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='BASIC';
SELECT COUNT(*) FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='BASIC';
SELECT * FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='TEST_CC';
SELECT COUNT(*) FROM XTORM.ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='TEST_CC';

--TOBE X394053
SELECT CONTENTCLASSID , count(*) AS 갯수 FROM ASYSCONTENTELEMENT a GROUP BY CONTENTCLASSID ;

SELECT * FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='LN_CC';
SELECT COUNT(*) FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='LN_CC';
SELECT * FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='DP_CC';
SELECT COUNT(*) FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='DP_CC';
SELECT * FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='CO_CC';
SELECT COUNT(*) FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='CO_CC';
SELECT * FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='BASIC';
SELECT COUNT(*) FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='BASIC';
SELECT * FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='TEST_CC';
SELECT COUNT(*) FROM ASYSCONTENTELEMENT a WHERE CONTENTCLASSID ='TEST_CC';
-----------------------------------------------------------------

-----------------XTORM.BIZ_INFO -> 각 업무 테이블--------------------

-- ASIS BIZ_INFO
SELECT * FROM XTORM.BIZ_INFO bi ;

-- TOBE 업무테이블 B394053
SELECT * FROM LOAN_TB; 
SELECT COUNT(*) FROM LOAN_TB; 
SELECT * FROM DEPOSIT_TB; 
SELECT COUNT(*) FROM DEPOSIT_TB; 
SELECT * FROM COMMON_TB; 
SELECT COUNT(*) FROM COMMON_TB; 
SELECT * FROM DOCUMENT_TB; 
SELECT * FROM IMAGE_TB; 
SELECT COUNT(*) FROM IMAGE_TB; 
SELECT * FROM EMPLOYEE_TB;

-- ASIS BIZ_INFO -> TOBE 업무 EMPLOYEE_TB 시작
INSERT ALL
 WHEN ENR_USER_ID LIKE '%%' THEN
 	INTO EMPLOYEE_TB (EMP_CD, EMP_NAME, ORG_CD, REG_DATE_INI, EMP_CD_INI, REG_DATE_FIN, EMP_CD_FIN)
 	VALUES (ENR_USER_ID, '-', ENR_ORG_CD, ENR_DTM, ENR_USER_ID, ENR_DTM,ENR_USER_ID)
 SELECT DISTINCT(ENR_USER_ID), ENR_ORG_CD, TO_DATE(ENR_DTM) AS ENR_DTM
 FROM XTORM.BIZ_INFO ;

SELECT count(DISTINCT(ENR_USER_ID)) FROM XTORM.BIZ_INFO bi ;
SELECT count(DISTINCT(ENR_ORG_CD)) FROM XTORM.BIZ_INFO bi ;
-- ASIS BIZ_INFO -> TOBE 업무 EMPLOYEE_TB 종료

-- ASIS BIZ_INFO -> TOBE 업무 IMAGE_TB 시작 
INSERT ALL
 WHEN CUST_NO LIKE '%%' THEN
 	INTO IMAGE_TB (ELEMENTID, SEQ_NO, TOY_KEY, DOC_CD, FILE_NM, EXTENSION, REG_DATE_INI, EMP_CD_INI, REG_DATE_FIN, EMP_CD_FIN)
 	VALUES (CUST_NO, CUST_NM, RRN_NO, ENR_DTM, ENR_USER_ID, ENR_DTM,ENR_USER_ID)
 SELECT DISTINCT(CUST_NO), CUST_NM, RRN_NO, ENR_USER_ID, TO_DATE(ENR_DTM) AS ENR_DTM
 FROM XTORM.BIZ_INFO ;

SELECT count(DISTINCT(CUST_NO)) FROM XTORM.BIZ_INFO bi ;
SELECT count(DISTINCT(RRN_NO)) FROM XTORM.BIZ_INFO bi ;
-- ASIS BIZ_INFO -> TOBE 업무 IMAGE_TB 종료

-------------------------------------------------------------------------------------------


