-- 테이블 생성 시작 --
DROP TABLE EMPLOYEE_TB ;
CREATE TABLE EMPLOYEE_TB 
( 
    EMP_CD     CHAR(6) NOT NULL PRIMARY KEY,
    EMP_NAME     VARCHAR(10) NOT NULL,
    ORG_CD      VARCHAR(10) NOT NULL,
    EMAIL		VARCHAR(30),
    PHONE_NO    VARCHAR(11), 
    REG_DATE_INI	char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_INI  CHAR(6) NOT NULL,
    REG_DATE_FIN   char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_FIN    CHAR(6) NOT NULL
);

DROP TABLE IMAGE_TB ;
CREATE TABLE IMAGE_TB 
( 
    ELEMENTID     CHAR(16) NOT NULL PRIMARY KEY,
    SEQ_NO     VARCHAR(10) NOT NULL,
    TOY_KEY      VARCHAR(16) NOT NULL,
    DOC_CD		CHAR(8) NOT NULL,
    LCAT_CD      CHAR(2) NOT NULL,
    FILE_NM    VARCHAR(30) NOT NULL, 
    EXTENSION   VARCHAR(10) NOT NULL,
    DEL_YN      char(1) DEFAULT 'N' CONSTRAINT DEL_YN_CH CHECK (DEL_YN IN ('Y', 'N')),
    REG_DATE_INI	char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_INI  CHAR(6) NOT NULL,
    REG_DATE_FIN   char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_FIN    CHAR(6) NOT NULL
);

DROP TABLE DOCUMENT_TB ;
CREATE TABLE DOCUMENT_TB 
( 
    DOC_CD     CHAR(8) NOT NULL PRIMARY KEY,
    LCAT_NM     VARCHAR(30) NOT NULL,
    LCAT_CD      CHAR(2) NOT NULL,
    MCAT_NM		VARCHAR(30) NOT NULL,
    MCAT_CD    CHAR(3) NOT NULL, 
    SCAT_NM   VARCHAR(30) NOT NULL,
    SCAT_CD    CHAR(3) NOT NULL,
    REG_DATE_INI	char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_INI  CHAR(6) NOT NULL,
    REG_DATE_FIN   char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_FIN    CHAR(6) NOT NULL
);

DROP TABLE COMMON_TB ;
CREATE TABLE COMMON_TB
( 
    TOY_KEY     VARCHAR(16) NOT NULL PRIMARY KEY,
    DOC_CD     CHAR(8) NOT NULL,
    CUST_NO      CHAR(10) NOT NULL,
    CUST_NM     VARCHAR(20) NOT NULL,
    RRN_NO      CHAR(32) NOT NULL,
    WARRANTY_PER   char(14) DEFAULT TO_CAHR(SYSDATE+n, 'YYYYMMDDHH24MISS'),
    REG_DATE_INI	char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_INI  CHAR(6) NOT NULL,
    REG_DATE_FIN   char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_FIN    CHAR(6) NOT NULL
);

DROP TABLE DEPOSIT_TB ;
CREATE TABLE DEPOSIT_TB
( 
    TOY_KEY     VARCHAR(16) NOT NULL PRIMARY KEY,
    DOC_CD     CHAR(8) NOT NULL,
    CUST_NO      CHAR(10) NOT NULL,
    CUST_NM     VARCHAR(20) NOT NULL,
    RRN_NO      CHAR(32) NOT NULL,
    WARRANTY_PER   char(14) DEFAULT TO_CAHR(SYSDATE+n, 'YYYYMMDDHH24MISS'),
    REG_DATE_INI	char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_INI  CHAR(6) NOT NULL,
    REG_DATE_FIN   char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_FIN    CHAR(6) NOT NULL
);

DROP TABLE LOAN_TB ;
CREATE TABLE LOAN_TB
( 
    TOY_KEY     VARCHAR(16) NOT NULL PRIMARY KEY,
    DOC_CD     CHAR(8) NOT NULL,
    CUST_NO      CHAR(10) NOT NULL,
    CUST_NM     VARCHAR(20) NOT NULL,
    RRN_NO      CHAR(32) NOT NULL,
    WARRANTY_PER   char(14) DEFAULT TO_CAHR(SYSDATE+n, 'YYYYMMDDHH24MISS'),
    REG_DATE_INI	char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_INI  CHAR(6) NOT NULL,
    REG_DATE_FIN   char(14) DEFAULT TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
    EMP_CD_FIN    CHAR(6) NOT NULL
);
-- 테이블 생성 종료 --